<template>
    <div>

    <span  class="option" v-if='country=="GB" ' value="44" Selected> (+47)</span>
    <span  class="option" v-if='country=="US" ' value="1"> (+44)</span>
        <span  class="option" v-if='country=="DZ" ' value="213"> (+213)</span>
        <span  class="option" v-if='country=="AD" ' value="376"> (+376)</span>
        <span  class="option" v-if='country=="AO" ' value="244"> (+244)</span>
        <span  class="option" v-if='country=="AI" ' value="1264"> (+1264)</span>
        <span  class="option" v-if='country=="AG" ' value="1268">  (+1268)</span>
        <span  class="option" v-if='country=="AR" ' value="54"> (+54)</span>
        <span  class="option" v-if='country=="AM" ' value="374"> (+374)</span>
        <span  class="option" v-if='country=="AW" ' value="297"> (+297)</span>
        <span  class="option" v-if='country=="AU" ' value="61"> (+61)</span>
        <span  class="option" v-if='country=="AT" ' value="43"> (+43)</span>
        <span  class="option" v-if='country=="AZ" ' value="994"> (+994)</span>
        <span  class="option" v-if='country=="BS" ' value="1242"> (+1242)</span>
        <span  class="option" v-if='country=="BH" ' value="973"> (+973)</span>
        <span  class="option" v-if='country=="BD" ' value="880"> (+880)</span>
        <span  class="option" v-if='country=="BB" ' value="1246"> (+1246)</span>
        <span  class="option" v-if='country=="BY" ' value="375"> (+375)</span>
        <span  class="option" v-if='country=="BE" ' value="32"> (+32)</span>
        <span  class="option" v-if='country=="BZ" ' value="501"> (+501)</span>
        <span  class="option" v-if='country=="BJ" ' value="229"> (+229)</span>
        <span  class="option" v-if='country=="BM" ' value="1441"> (+1441)</span>
        <span  class="option" v-if='country=="BT" ' value="975"> (+975)</span>
        <span  class="option" v-if='country=="BO" ' value="591"> (+591)</span>
        <span  class="option" v-if='country=="BA" ' value="387">  (+387)</span>
        <span  class="option" v-if='country=="BW" ' value="267"> (+267)</span>
        <span  class="option" v-if='country=="BR" ' value="55"> (+55)</span>
        <span  class="option" v-if='country=="BN" ' value="673"> (+673)</span>
        <span  class="option" v-if='country=="BG" ' value="359"> (+359)</span>
        <span  class="option" v-if='country=="BF" ' value="226">  (+226)</span>
        <span  class="option" v-if='country=="BI" ' value="257"> (+257)</span>
        <span  class="option" v-if='country=="KH" ' value="855"> (+855)</span>
        <span  class="option" v-if='country=="CM" ' value="237"> (+237)</span>
        <span  class="option" v-if='country=="CA" ' value="1"> (+1)</span>
        <span  class="option" v-if='country=="CV" ' value="238">   (+238)</span>
        <span  class="option" v-if='country=="KY" ' value="1345">  (+1345)</span>
        <span  class="option" v-if='country=="CF" ' value="236">   (+236)</span>
        <span  class="option" v-if='country=="CL" ' value="56"> (+56)</span>
        <span  class="option" v-if='country=="CN" ' value="86"> (+86)</span>
        <span  class="option" v-if='country=="CO" ' value="57"> (+57)</span>
        <span  class="option" v-if='country=="KM" ' value="269"> (+269)</span>
        <span  class="option" v-if='country=="CG" ' value="242"> (+242)</span>
        <span  class="option" v-if='country=="CK" ' value="682">  (+682)</span>
        <span  class="option" v-if='country=="CR" ' value="506">  (+506)</span>
        <span  class="option" v-if='country=="HR" ' value="385"> (+385)</span>
        <span  class="option" v-if='country=="CU" ' value="53"> (+53)</span>
        <span  class="option" v-if='country=="CY" ' value="90392">  (+90392)</span>
        <span  class="option" v-if='country=="CY" ' value="357">  (+357)</span>
        <span  class="option" v-if='country=="CZ" ' value="42">  (+42)</span>
        <span  class="option" v-if='country=="DK" ' value="45"> (+45)</span>
        <span  class="option" v-if='country=="DJ" ' value="253"> (+253)</span>
        <span  class="option" v-if='country=="DM" ' value="1809"> (+1809)</span>
        <span  class="option" v-if='country=="DO" ' value="1809">  (+1809)</span>
        <span  class="option" v-if='country=="EC" ' value="593"> (+593)</span>
        <span  class="option" v-if='country=="EG" ' value="20"> (+20)</span>
        <span  class="option" v-if='country=="SV" ' value="503">(+503)</span>
        <span  class="option" v-if='country=="GQ" ' value="240">  (+240)</span>
        <span  class="option" v-if='country=="ER" ' value="291"> (+291)</span>
        <span  class="option" v-if='country=="EE" ' value="372"> (+372)</span>
        <span  class="option" v-if='country=="ET" ' value="251"> (+251)</span>
        <span  class="option" v-if='country=="FK" ' value="500">  (+500)</span>
        <span  class="option" v-if='country=="FO" ' value="298">  (+298)</span>
        <span  class="option" v-if='country=="FJ" ' value="679"> (+679)</span>
        <span  class="option" v-if='country=="FI" ' value="358"> (+358)</span>
        <span  class="option" v-if='country=="FR" ' value="33"> (+33)</span>
        <span  class="option" v-if='country=="GF" ' value="594">  (+594)</span>
        <span  class="option" v-if='country=="PF" ' value="689">  (+689)</span>
        <span  class="option" v-if='country=="GA" ' value="241"> (+241)</span>
        <span  class="option" v-if='country=="GM" ' value="220"> (+220)</span>
        <span  class="option" v-if='country=="GE" ' value="7880"> (+7880)</span>
        <span  class="option" v-if='country=="DE" ' value="49"> (+49)</span>
        <span  class="option" v-if='country=="GH" ' value="233"> (+233)</span>
        <span  class="option" v-if='country=="GI" ' value="350"> (+350)</span>
        <span  class="option" v-if='country=="GR" ' value="30"> (+30)</span>
        <span  class="option" v-if='country=="GL" ' value="299"> (+299)</span>
        <span  class="option" v-if='country=="GD" ' value="1473"> (+1473)</span>
        <span  class="option" v-if='country=="GP" ' value="590"> (+590)</span>
        <span  class="option" v-if='country=="GU" ' value="671"> (+671)</span>
        <span  class="option" v-if='country=="GT" ' value="502"> (+502)</span>
        <span  class="option" v-if='country=="GN" ' value="224"> (+224)</span>
        <span  class="option" v-if='country=="GW" ' value="245">  (+245)</span>
        <span  class="option" v-if='country=="GY" ' value="592"> (+592)</span>
        <span  class="option" v-if='country=="HT" ' value="509"> (+509)</span>
        <span  class="option" v-if='country=="HN" ' value="504"> (+504)</span>
        <span  class="option" v-if='country=="HK" ' value="852">  (+852)</span>
        <span  class="option" v-if='country=="HU" ' value="36"> (+36)</span>
        <span  class="option" v-if='country=="IS" ' value="354"> (+354)</span>
        <span  class="option" v-if='country=="IN" ' value="91"> (+91)</span>
        <span  class="option" v-if='country=="ID" ' value="62"> (+62)</span>
        <span  class="option" v-if='country=="IR" ' value="98"> (+98)</span>
        <span  class="option" v-if='country=="IQ" ' value="964"> (+964)</span>
        <span  class="option" v-if='country=="IE" ' value="353"> (+353)</span>
        <span  class="option" v-if='country=="IT" ' value="39"> (+39)</span>
        <span  class="option" v-if='country=="JM" ' value="1876"> (+1876)</span>
        <span  class="option" v-if='country=="JP" ' value="81"> (+81)</span>
        <span  class="option" v-if='country=="JO" ' value="962"> (+962)</span>
        <span  class="option" v-if='country=="KZ" ' value="7"> (+7)</span>
        <span  class="option" v-if='country=="KE" ' value="254"> (+254)</span>
        <span  class="option" v-if='country=="KI" ' value="686"> (+686)</span>
        <span  class="option" v-if='country=="KP" ' value="850">  (+850)</span>
        <span  class="option" v-if='country=="KR" ' value="82">  (+82)</span>
        <span  class="option" v-if='country=="KW" ' value="965"> (+965)</span>
        <span  class="option" v-if='country=="KG" ' value="996"> (+996)</span>
        <span  class="option" v-if='country=="LA" ' value="856"> (+856)</span>
        <span  class="option" v-if='country=="LV" ' value="371"> (+371)</span>
        <span  class="option" v-if='country=="LB" ' value="961"> (+961)</span>
        <span  class="option" v-if='country=="LS" ' value="266"> (+266)</span>
        <span  class="option" v-if='country=="LR" ' value="231"> (+231)</span>
        <span  class="option" v-if='country=="LY" ' value="218"> (+218)</span>
        <span  class="option" v-if='country=="span" ' value="417"> (+417)</span>
        <span  class="option" v-if='country=="LT" ' value="370"> (+370)</span>
        <span  class="option" v-if='country=="LU" ' value="352"> (+352)</span>
        <span  class="option" v-if='country=="MO" ' value="853"> (+853)</span>
        <span  class="option" v-if='country=="MK" ' value="389"> (+389)</span>
        <span  class="option" v-if='country=="MG" ' value="261"> (+261)</span>
        <span  class="option" v-if='country=="MW" ' value="265"> (+265)</span>
        <span  class="option" v-if='country=="MY" ' value="60"> (+60)</span>
        <span  class="option" v-if='country=="MV" ' value="960"> (+960)</span>
        <span  class="option" v-if='country=="ML" ' value="223"> (+223)</span>
        <span  class="option" v-if='country=="MT" ' value="356"> (+356)</span>
        <span  class="option" v-if='country=="MH" ' value="692">  (+692)</span>
        <span  class="option" v-if='country=="MQ" ' value="596"> (+596)</span>
        <span  class="option" v-if='country=="MR" ' value="222"> (+222)</span>
        <span  class="option" v-if='country=="YT" ' value="269"> (+269)</span>
        <span  class="option" v-if='country=="MX" ' value="52"> (+52)</span>
        <span  class="option" v-if='country=="FM" ' value="691"> (+691)</span>
        <span  class="option" v-if='country=="MD" ' value="373"> (+373)</span>
        <span  class="option" v-if='country=="MC" ' value="377"> (+377)</span>
        <span  class="option" v-if='country=="MN" ' value="976"> (+976)</span>
        <span  class="option" v-if='country=="MS" ' value="1664"> (+1664)</span>
        <span  class="option" v-if='country=="MA" ' value="212"> (+212)</span>
        <span  class="option" v-if='country=="MZ" ' value="258"> (+258)</span>
        <span  class="option" v-if='country=="MN" ' value="95"> (+95)</span>
        <span  class="option" v-if='country=="NA" ' value="264"> (+264)</span>
        <span  class="option" v-if='country=="NR" ' value="674"> (+674)</span>
        <span  class="option" v-if='country=="NP" ' value="977"> (+977)</span>
        <span  class="option" v-if='country=="NL" ' value="31"> (+31)</span>
        <span  class="option" v-if='country=="NC" ' value="687">  (+687)</span>
        <span  class="option" v-if='country=="NZ" ' value="64">  (+64)</span>
        <span  class="option" v-if='country=="NI" ' value="505"> (+505)</span>
        <span  class="option" v-if='country=="NE" ' value="227"> (+227)</span>
        <span  class="option" v-if='country=="NG" ' value="234"> (+234)</span>
        <span  class="option" v-if='country=="NU" ' value="683"> (+683)</span>
        <span  class="option" v-if='country=="NF" ' value="672">  (+672)</span>
        <span  class="option" v-if='country=="NP" ' value="670">  (+670)</span>
        <span  class="option" v-if='country=="NO" ' value="47"> (+47)</span>
        <span  class="option" v-if='country=="OM" ' value="968"> (+968)</span>
        <span  class="option" v-if='country=="PW" ' value="680"> (+680)</span>
        <span  class="option" v-if='country=="PA" ' value="507"> (+507)</span>
        <span  class="option" v-if='country=="PG" ' value="675">   (+675)</span>
        <span  class="option" v-if='country=="PY" ' value="595"> (+595)</span>
        <span  class="option" v-if='country=="PE" ' value="51"> (+51)</span>
        <span  class="option" v-if='country=="PH" ' value="63"> (+63)</span>
        <span  class="option" v-if='country=="PL" ' value="48"> (+48)</span>
        <span  class="option" v-if='country=="PT" ' value="351"> (+351)</span>
        <span  class="option" v-if='country=="PR" ' value="1787">  (+1787)</span>
        <span  class="option" v-if='country=="QA" ' value="974"> (+974)</span>
        <span  class="option" v-if='country=="RE" ' value="262"> (+262)</span>
        <span  class="option" v-if='country=="RO" ' value="40"> (+40)</span>
        <span  class="option" v-if='country=="RU" ' value="7"> (+7)</span>
        <span  class="option" v-if='country=="RW" ' value="250"> (+250)</span>
        <span  class="option" v-if='country=="SM" ' value="378">  (+378)</span>
        <span  class="option" v-if='country=="ST" ' value="239">   (+239)</span>
        <span  class="option" v-if='country=="SA" ' value="966">  (+966)</span>
        <span  class="option" v-if='country=="SN" ' value="221"> (+221)</span>
        <span  class="option" v-if='country=="CS" ' value="381"> (+381)</span>
        <span  class="option" v-if='country=="SC" ' value="248"> (+248)</span>
        <span  class="option" v-if='country=="SL" ' value="232">  (+232)</span>
        <span  class="option" v-if='country=="SG" ' value="65"> (+65)</span>
        <span  class="option" v-if='country=="SK" ' value="421">  (+421)</span>
        <span  class="option" v-if='country=="SI" ' value="386"> (+386)</span>
        <span  class="option" v-if='country=="SB" ' value="677">  (+677)</span>
        <span  class="option" v-if='country=="SO" ' value="252"> (+252)</span>
        <span  class="option" v-if='country=="ZA" ' value="27">  (+27)</span>
        <span  class="option" v-if='country=="ES" ' value="34"> (+34)</span>
        <span  class="option" v-if='country=="LK" ' value="94"> (+94)</span>
        <span  class="option" v-if='country=="SH" ' value="290"> (+290)</span>
        <span  class="option" v-if='country=="KN" ' value="1869"> (+1869)</span>
        <span  class="option" v-if='country=="SC" ' value="1758"> (+1758)</span>
        <span  class="option" v-if='country=="SD" ' value="249"> (+249)</span>
        <span  class="option" v-if='country=="SR" ' value="597"> (+597)</span>
        <span  class="option" v-if='country=="SZ" ' value="268"> (+268)</span>
        <span  class="option" v-if='country=="SE" ' value="46"> (+46)</span>
        <span  class="option" v-if='country=="CH" ' value="41"> (+41)</span>
        <span  class="option" v-if='country=="SI" ' value="963"> (+963)</span>
        <span  class="option" v-if='country=="TW" ' value="886"> (+886)</span>
        <span  class="option" v-if='country=="TJ" ' value="7"> (+7)</span>
        <span  class="option" v-if='country=="TH" ' value="66"> (+66)</span>
        <span  class="option" v-if='country=="TG" ' value="228"> (+228)</span>
        <span  class="option" v-if='country=="TO" ' value="676"> (+676)</span>
        <span  class="option" v-if='country=="TT" ' value="1868"> (+1868)</span>
        <span  class="option" v-if='country=="TN" ' value="216"> (+216)</span>
        <span  class="option" v-if='country=="TR" ' value="90"> (+90)</span>
        <span  class="option" v-if='country=="TM" ' value="7"> (+7)</span>
        <span  class="option" v-if='country=="TM" ' value="993"> (+993)</span>
        <span  class="option" v-if='country=="TC" ' value="1649"> (+1649)</span>
        <span  class="option" v-if='country=="TV" ' value="688"> (+688)</span>
        <span  class="option" v-if='country=="UG" ' value="256"> (+256)</span>
        <span  class="option" v-if='country=="GB" ' value="44"> (+44)</span>
        <span  class="option" v-if='country=="UA" ' value="380"> (+380)</span>
        <span  class="option" v-if='country=="AE" ' value="971"> (+971)</span>
        <span  class="option" v-if='country=="UY" ' value="598"> (+598)</span>
        <span  class="option" v-if='country=="US" ' value="1"> (+1)</span>
        <span  class="option" v-if='country=="UZ" ' value="7"> (+7)</span>
        <span  class="option" v-if='country=="VU" ' value="678"> (+678)</span>
        <span  class="option" v-if='country=="VA" ' value="379">  (+379)</span>
        <span  class="option" v-if='country=="VE" ' value="58"> (+58)</span>
        <span  class="option" v-if='country=="VN" ' value="84"> (+84)</span>
        <span  class="option" v-if='country=="VG" ' value="84"> (+1284)</span>
        <span  class="option" v-if='country=="VI" ' value="84"> (+1340)</span>
        <span  class="option" v-if='country=="WF" ' value="681"> (+681)</span>
        <span  class="option" v-if='country=="YE" ' value="969"> (+969)</span>
        <span  class="option" v-if='country=="YE" ' value="967">(+967)</span>
        <span  class="option" v-if='country=="ZM" ' value="260"> (+260)</span>
        <span  class="option" v-if='country=="ZW" ' value="263"> (+263)</span>




    </div>
</template>


<script>
export default {
    props:{country:String},
    
}
</script>